pharo-contributions/mutalk

src/MuTalk-Model/MethodMutation.class.st
src/MuTalk-Model/MutantOperator.class.st
src/MuTalk-TestResources/ClassForTestingCoverage.class.st
src/MuTalk-Tests/MethodMutationTest.class.st

I extract the old and the new nodes when the mutated sourcecode is generating in `MutantOperator>>#modifiedSourceFor:with:number:`. 
Then, I set these values to `mutatedNode` and `nodeToMutate` variables in `MethodMutation`. 
So, there is no need to call `lookupForNodes` anymore.

Fix issue #4

---

src/MuTalk-Model/MethodMutation.class.st
src/MuTalk-Model/MutantEvaluation.class.st
src/MuTalk-Model/MutationTestingAnalysis.class.st
src/MuTalk-Model/TestCaseReference.class.st
src/MuTalk-Model/TestResult.extension.st
src/MuTalk-Tests/MethodInstallerTest.class.st
src/MuTalk-Tests/MethodMutationTest.class.st
src/MuTalk-Tests/TestCaseReferenceTest.class.st

When the process is executed, MethodMutations are created.
It is now also giving it the test cases that need to be executed for this mutation.
This fix also moves the execution logic to MethodMutation, allowing for a mutation to be re executed after the full process has been executed.
This allows for a better post run analysis of the mutant, regardless of if they survived or not.

[improvement] move mutant execution logic to be able to rerun it

---

src/BaselineOfMuTalk/BaselineOfMuTalk.class.st

[Question]
As the install for the Pharo versiions 7, 8, 9 and 10 is exactly the same
```st
spec for: #'pharoY.X' do: [
spec package: 'TestCoverage'.
spec group: 'testCoverage' with: #('TestCoverage') ]
```
can we remove that and replace it with ?
```st
package: 'TestCoverage';
package: 'MuTalk-Model' with: [ spec requires: #('TestCoverage')];
```

Refactoring baseline

---

src/BaselineOfMuTalk/BaselineOfMuTalk.class.st
src/MuTalk-SpecUI/MutationResultsPresenter.class.st
src/MuTalk-SpecUI/MutationTestingGeneralResult.extension.st
src/MuTalk-SpecUI/package.st

Added presenter for visualising better the results of the test mutation.
If we inspect `analysis generalResult` we will get this inspector:
I also modified the baseline to load the inspector extension only in Pharo 10 and 9. Because for the other Pharo versions Spec2 is not available there.

Adding inspector extension

---

src/MuTalk-Model/MethodMutation.class.st
src/MuTalk-Model/MutantOperator.class.st
src/MuTalk-Tests/MethodMutationTest.class.st
src/MuTalk-Tests/MutantKillingSuggesionTest.class.st

AST nodes are only held for testing purposes but are not used in the model.
These changes make that AST nodes are computed on demand instead of cached.
This makes that mid-sized analyses take less than half of the space.
In the example below, memory consumption (measured using https://github.com/tesonep/spaceAndTime) went down from 120MB to 50MB roughly.
Still, we need to remove the cached source code that takes also some space, it will come tomorrow.
Without these optimisations, it seems unfeasible for large programs with tons of mutations.
```smalltalk
testCases :=  { VMJittedPrimitiveAtPutTest  }.
classesToMutate := { 
CogARMv8Compiler }.
analysis := MutationTestingAnalysis
testCasesFrom: testCases
mutating: classesToMutate
using: MutantOperator contents
with: …
```

Optimising mutations to not hold to AST nodes

---

src/MuTalk-Tests/MutationTestingPercentageOfMutantsBudgetTest.class.st

Fixes #38
Added a test in case the percentage doesn't give an exact number of mutants (e.g. 5.25 mutants).
In this case, 6 mutants are evaluated, and the effective percentage of mutants evaluated is greater than the one given (it works the same way for time budget).

Added test for not exact percentage mutant selection

---

.smalltalk.ston
src/MuTalk-Model/MethodMutation.class.st
src/MuTalk-Model/MutantEvaluation.class.st
src/MuTalk-Model/MutationTestingAnalysis.class.st
src/MuTalk-TestResources/AuxiliarTestClassForContinuingTestsExecutionAfterFirstFail.class.st
src/MuTalk-Tests/MethodMutationTest.class.st
src/MuTalk-Tests/MutationTestingAnalysisTest.class.st
src/MuTalk-Tests/NullMutation.class.st
src/MuTalk-Tests/TestCasesSelectionStrategyTest.class.st

Add an option to allow all the tests to be executed on mutants, even after the first error or fail.
Default behavior does not change.

Allow analysis to continue even after the first test error

---

src/MuTalk-Model/MethodMutation.class.st

Code changes is not polluted by the mutants.

Disable epicea monitoring during mutant evaluation

---

src/MuTalk-Model/CoverageAnalysis.class.st
src/MuTalk-Model/MutationTestingAnalysis.class.st

And some incompatible with Pharo12

Fix: replace class side API implementation

---

src/MuTalk-Model/MTAnalysisFileLogger.class.st
src/MuTalk-Tests/MTAnalysisFileLoggerTest.class.st

Updated `MTAnalysisFileLogger` with new file managing system.
You can use it like that: 
```smalltalk
analysis := MTAnalysis new
classesToMutate: { UUID };
testClasses: { UUIDTest };
logger: (MTAnalysisFileLogger toFileNamed: 'log.txt').
analysis run
```

Updated file logger

---

src/MuTalk-Model/MTTestCaseReference.class.st
src/MuTalk-Utilities/MTMatrix.class.st

You can now generate a heatmap for `MTMatrix`.
It groups the mutations by operator and the tests by class, and represents the percentage of the mutations from a given operator that are killed by the tests from a given class.
```smalltalk
matrix := MTMatrix forClasses: { UUID } andTests: {
UUIDTest.
UUIDPrimitivesTest }.
matrix build.
matrix generateHeatmap
```

Add heatmap to MTMatrix

---

src/MuTalk-Model/MTAnalysis.class.st
src/MuTalk-Model/MTTestCaseReference.class.st
src/MuTalk-Model/MTTestCasesSelectionStrategy.class.st
src/MuTalk-TestResources/MTAuxiliarParametrizedTestClass.class.st
src/MuTalk-Tests/MTAnalysisTest.class.st
src/MuTalk-Tests/MTMethodMutationTest.class.st
src/MuTalk-Tests/MTTestCaseReferenceTest.class.st
src/MuTalk-Tests/MTTestCasesSelectionStrategyTest.class.st
src/MuTalk-Tests/MTTimeTestFilterTest.class.st
src/MuTalk-Utilities/MTMatrix.class.st

Fixes #88 
Now `MTAnalysis` retrieves correctly all tests cases from parametrized tests.
I also refactored a bit `MTTestCaseReference` so that it now has the test case as instance variable rather than the class and the selector.

Mutalk handles parametrized tests correctly

---

src/MuTalk-Model/MTAnalysis.class.st
src/MuTalk-Model/MTBlockTestFilter.class.st
src/MuTalk-Model/MTFreeTestFilter.class.st
src/MuTalk-Model/MTGeneralResult.class.st
src/MuTalk-Model/MTPragmaRejectionTestFilter.class.st
src/MuTalk-Model/MTPragmaSelectionTestFilter.class.st
src/MuTalk-Model/MTPragmaTestFilter.class.st
src/MuTalk-Model/MTTestFilter.class.st
src/MuTalk-Model/MTTimeTestFilter.class.st
src/MuTalk-SpecUI/MTExcludedTestsPresenter.class.st
src/MuTalk-SpecUI/MTFilteredTestsPresenter.class.st
src/MuTalk-SpecUI/MTGeneralResult.extension.st
src/MuTalk-Tests/MTPragmaSelectionTestFilterTest.class.st

Also shows the reason and the code of the selected test.

General result shows filtered tests

---

README.md
src/MuTalk-CI/MTCoveragePropagationPreparation.class.st
src/MuTalk-Model/MTAnalysis.class.st
src/MuTalk-Model/MTRedTestFilter.class.st
src/MuTalk-Model/MTTestCaseReference.class.st
src/MuTalk-Model/MTTestFilter.class.st
src/MuTalk-TestResources/MTAuxiliarTestClassForRedTestFilter.class.st
src/MuTalk-Tests/MTRedTestFilterTest.class.st
src/MuTalk-Tests/MTTestCaseReferenceTest.class.st
src/MuTalk-Tests/MTTestCasesSelectionStrategyTest.class.st
src/MuTalk-Tests/MTTimeTestFilterTest.class.st

Fixes #28
Added `MTRedTestFilter`, a test filter that allows to run the analysis even if there are failing tests during the initial test run.
Refactored by the way:
* how the analysis apply test filters
* `MTTestCaseReference` to include the last result as instance variable and the `#run` methods by moving the ` MTTestsWithErrorsException` (when there are failing tests in the initial test run) management in `MTAnalysis`

Red test filter

---

README.md
src/MuTalk-Model/MTBlockTestFilter.class.st
src/MuTalk-Model/MTPragmaRejectionTestFilter.class.st
src/MuTalk-Model/MTPragmaSelectionTestFilter.class.st
src/MuTalk-Model/MTPragmaTestFilter.class.st
src/MuTalk-Model/MTRedTestFilter.class.st
src/MuTalk-Model/MTTestFilter.class.st
src/MuTalk-Model/MTTimeTestFilter.class.st

Also I will release v2.2.1, hence why I updated the readme

Fix unimplemented methods and small refactoring for test filters

---

src/MuTalk-TestResources/MTTestResourceClassForTestingCoverage.class.st

Fixes #103
The problem seemed to be that, since `anUncoveredMethod` is called in the `setUp`, it was called during the coverage analysis and so it was treated as being part of the tests. But since `setUp` is called only the first time, that's why the test was failing only the first time.
This way I make sure that the tests won't fail.

Fix testCoveredMethods

---

src/BaselineOfMuTalk/BaselineOfMuTalk.class.st
src/MuTalk-Model/MTAllMutantGenerationStrategy.class.st
src/MuTalk-Model/MTAnalysis.class.st
src/MuTalk-Model/MTCoverageAnalysis.class.st
src/MuTalk-Model/MTMutantEvaluation.class.st
src/MuTalk-TestResources/MTAuxiliarClassForAnalysisWithExtensionMethods.class.st
src/MuTalk-TestResourcesForExtensionMethods/MTAuxiliarClassForAnalysisWithExtensionMethods.extension.st
src/MuTalk-TestResourcesForExtensionMethods/package.st
src/MuTalk-Tests/MTAnalysisTest.class.st
src/MuTalk-Tests/MTTestCoverageAnalysis.class.st
src/MuTalk-Utilities-Tests/MTNonMutatedMethodsAnalysisTest.class.st
src/MuTalk-Utilities/MTMutantOperatorAnalysis.class.st
src/MuTalk-Utilities/MTNonMutatedMethodsAnalysis.class.st
src/MuTalk-Utilities/MTUtilityAnalysis.class.st

Fixes #30
Refactored `MTAnalysis` and `MTCoverageAnalysis` to use methods instead of classes.
Also, extension methods are now not mutated when using classes (`classesToMutate:) ` with `MTAnalysis`, but are when using packages (`packagesToMutate:`).

Analysis uses methods instead of classes & extension methods are ignored if not from package

---

src/MuTalk-Model/MTAnalysis.class.st
src/MuTalk-Tests/MTAnalysisTest.class.st

Fixes #113
Changed the time for default budget to 5 minutes, because adjusting it with the tests run time was too complicated.

Changed default budget

---

src/MuTalk-CI-Tests/MTCoveragePropagationPreparationTest.class.st
src/MuTalk-Model/MTAnalysis.class.st
src/MuTalk-Model/MTAnalysisLogger.class.st
src/MuTalk-Model/MTFileLogger.class.st
src/MuTalk-Model/MTMethodMutation.class.st
src/MuTalk-Model/MTMutantGenerationStrategy.class.st
src/MuTalk-Model/MTNullLogger.class.st
src/MuTalk-Model/MTProgressBarLogger.class.st
src/MuTalk-Model/MTStreamLogger.class.st
src/MuTalk-Model/MTTestCaseReference.class.st
src/MuTalk-Model/MTTestSuiteWrappedForCoverage.class.st
src/MuTalk-Tests/MTMockAnalysisLogger.class.st

Fixes #89 fixes #112
Added a new logger that works as a progress bar. Analysis now uses it as default logger.
Also refactored a bit all the logging system.

Added a progress bar as a logger

---

src/BaselineOfMuTalk/BaselineOfMuTalk.class.st
src/MuTalk-Examples/MTAnalysis.extension.st
src/MuTalk-Examples/MyVehicle.class.st
src/MuTalk-Examples/MyVehicleTest.class.st
src/MuTalk-Examples/package.st
src/MuTalk-Model/MTAnalysis.class.st
src/MuTalk-Tests/MTTimeBudgetTest.class.st
src/MuTalk-Utilities/MTMatrix.class.st
src/MuTalk-Utilities/MTUtilityAnalysis.class.st

Package `MuTalk-Examples` contains a class and a test class used for the MuTalk chapter, and executable scripts as extension methods in `MTAnalysis` class side.
Small changes include :
- don't log the mutant generation if the mutations are already given (mutations are not nil)
- heat map color palette changed to red - yellow - green
- setter for `mtAnalysis` in `MTUtilityAnalysis` class

Example for the MuTalk chapter and small changes

---

src/MuTalk-Model/MTAnalysis.class.st
src/MuTalk-Utilities/MTUtilityAnalysis.class.st

Fixes #123 
Those analysis don't use tests, so the warning should not interrupt them.  
The current solution is certainly not perfect, so I'm open to better implementation idea.

Utility analysis ignore the "no tests" warning

---

src/MuTalk-Model/MTAnalysis.class.st

Added accessors methods to mutant selection strategies for `MTAnalysis`, even though they are attributes of mutant *generation* strategies, to make them easier to manipulate from the analysis object.  
Also renamed a method with unclear name.

Mutant selection strategies more easily accessible and method rename

---

src/MuTalk-Examples/MTAnalysis.extension.st
src/MuTalk-Utilities/MTAnalysis.extension.st
src/MuTalk-Utilities/MTMatrix.class.st

Changed heatmap generation to be able to group mutations by whichever block is given.
Added three configurations : mutations grouped by operator (the previous default), by class or by method.

More customizable heatmaps

---

src/BaselineOfMuTalk/BaselineOfMuTalk.class.st
src/MuTalk-Examples-Tests/MyVehicleTest.class.st
src/MuTalk-Examples-Tests/package.st

Also wondering if examples packages should be loaded by default in MuTalk or not. They can be useful for new users to see what an analysis looks like, but past that they're not necessary to have.

Moved MyVehicleTest to dedicated test package
